src/PersonApplication/Models/CreateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PersonApplication.Models
{
    public class CreateViewModel
    {
        [Display(Name = "Person Name")]
        [Required]
        [StringLength(50)]
        public string PersonName { get; set; }

        [Display(Name = "Date Added")]
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateAdded { get; set; }

        [Required]
        [Display(Name = "Group")]
        public string SelectedGroupId { get; set; }
        public IEnumerable<SelectListItem> Group { get; set; }
    }
}

src/PersonApplication/Models/ErrorViewModel.cs
using System;

namespace PersonApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/PersonApplication/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonApplication.Models
{
    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

src/PersonApplication/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PersonApplication.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateAdded { get; set; }
        public Group Group { get; set; }
    }
}

src/PersonApplication/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PersonApplication.DataAccess;
using PersonApplication.Models;

namespace PersonApplication.Controllers
{
    public class PersonController : Controller
    {
        private readonly ILogger<PersonController> _logger;
        private readonly IPersonRespository _personRepository;

        public PersonController(ILogger<PersonController> logger, IPersonRespository _repository)
        {
            _logger = logger;
            _personRepository = _repository;
        }

        // GET: Person
        public async Task<IActionResult> Index()
        {
            try
            {
                var persons = await _personRepository.GetAllPersons();

                var model = persons.Select(x => new Person
                {
                    Id = x.Id,
                    Name = x.Name,
                    Group = new Group
                    {
                        Id = x.Group.Id,
                        Name = x.Group.Name
                    },
                    DateAdded = x.DateAdded

                });

                return View(model);
            }
            catch(Exception e)
            {
                _logger.LogError(e, "Error whilst displaying all persons on home page");
                throw;
            }
        }


        // GET: Person/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                var viewModel = new CreateViewModel();
                var groups = await _personRepository.GetAllGroups();

                viewModel.Group = groups.Select(
                    g => new SelectListItem
                    {
                        Value = g.Id.ToString(),
                        Text = g.Name
                    }).ToList();

                return View(viewModel);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error whilst display of Add new person page");
                throw;
            }
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateViewModel createPerson)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int intGroupId;
                    if (!int.TryParse(createPerson.SelectedGroupId, out intGroupId))
                        return View(createPerson);

                    //create person from person view model
                    var person = new Entities.Models.Person
                    {
                        Name = createPerson.PersonName,
                        DateAdded = createPerson.DateAdded,
                        Group = new Entities.Models.Group
                        {
                            Id = intGroupId
                        }
                    };
                    await _personRepository.AddPerson(person);
                    return RedirectToAction(nameof(Index));
                }
                return View(createPerson);
            }
            catch(Exception e)
            {
                _logger.LogError(e, $"Error whilst creating new person - {createPerson.PersonName}");
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Search(string SearchName, string SearchGroup)
        {
            try
            {
                if (String.IsNullOrEmpty(SearchName) && String.IsNullOrEmpty(SearchGroup))
                    return Content("Please enter person name or group");

                var persons = await _personRepository.Search(SearchName, SearchGroup);

                var model = persons.Select(x => new Person
                {
                    Id = x.Id,
                    Name = x.Name,
                    Group = new Group
                    {
                        Id = x.Group.Id,
                        Name = x.Group.Name
                    },
                    DateAdded = x.DateAdded

                });

                return PartialView("Index", model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"Error whilst searching for search params - search name {SearchName}, search group {SearchGroup}");
                throw;
            }
        }
    }
}

src/PersonApplication/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PersonApplication.Models;

namespace PersonApplication.Controllers
{
    public class SiteController : Controller
    {
        private readonly ILogger<SiteController> _logger;

        public SiteController(ILogger<SiteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/PersonApplication/Views/Person/Create.cshtml
@model PersonApplication.Models.CreateViewModel

@{
    ViewData["Title"] = "Add Person";
}

<h1>Add Person</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAdded" class="control-label"></label>
                <input asp-for="DateAdded" class="form-control" value="@DateTime.Today.ToShortDateString()" />
                <span asp-validation-for="DateAdded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                @Html.DropDownListFor(x => Model.SelectedGroupId, new SelectList(Model.Group, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Person List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/PersonApplication/Views/Person/Index.cshtml
@model IEnumerable<PersonApplication.Models.Person>

@{
    ViewData["Title"] = "Home";
}

<h1>Person and Groups</h1>

<p>
    <a asp-action="Create">Add Person</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group.Name)
            </td>
        </tr>
}
    </tbody>
</table>

src/PersonApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Person Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Person" asp-action="Index">Person Application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <div class="col-md-5">
                </div>
                <div class="col-md-2">
                    Name: @Html.TextBox("SearchName")
                </div>
                <div class="col-md-2">
                    Group: @Html.TextBox("SearchGroup")
                </div>
                <div class="col-md-2" >
                    <br/>
                    <input type="button" value="Search" id="Search" />
                    <br />
                    <span id="msg" style="color:red;" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" id="viewBody">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PersonApplication - <a asp-area="" asp-controller="Site" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $('#Search').click(function () {
            var url = "/Person/Search";
            var name = $("#SearchName").val();
            var group = $("#SearchGroup").val();
            $.post(url, { SearchName: name, SearchGroup: group }, function (data) {
                if (data.indexOf("Person and Groups") < 0)
                    $("#msg").html(data);
                else {
                    $("#viewBody").html(data);
                    $("#msg").html('');
                }
            });
        })
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>